# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Classes_AllOthers.py
# Created on: 2019-01-15 09:52:25.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: Classes_AllOthers <Output_Folder> <Output_Feature_Class__12_> <Output_Feature_Class__11_> <Output_Feature_Class__10_> <Output_Feature_Class__9_> <Output_Feature_Class__8_> <Output_Feature_Class__7_> <Output_Feature_Class__6_> <Output_Feature_Class__5_> <Output_Feature_Class__4_> <Output_Feature_Class__3_> <Output_Feature_Class__2_> <Output_Feature_Class> <Input_RTP> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
Output_Folder = arcpy.GetParameterAsText(0)
if Output_Folder == '#' or not Output_Folder:
    Output_Folder = "C:\\Kelsey\\Fall_Sem\\WCW_3m\\elev_k" # provide a default value if unspecified

Output_Feature_Class__12_ = arcpy.GetParameterAsText(1)
if Output_Feature_Class__12_ == '#' or not Output_Feature_Class__12_:
    Output_Feature_Class__12_ = "wcw_s14x_12b.shp" # provide a default value if unspecified

Output_Feature_Class__11_ = arcpy.GetParameterAsText(2)
if Output_Feature_Class__11_ == '#' or not Output_Feature_Class__11_:
    Output_Feature_Class__11_ = "wcw_s14x_11b.shp" # provide a default value if unspecified

Output_Feature_Class__10_ = arcpy.GetParameterAsText(3)
if Output_Feature_Class__10_ == '#' or not Output_Feature_Class__10_:
    Output_Feature_Class__10_ = "wcw_s14x_10bshp.shp" # provide a default value if unspecified

Output_Feature_Class__9_ = arcpy.GetParameterAsText(4)
if Output_Feature_Class__9_ == '#' or not Output_Feature_Class__9_:
    Output_Feature_Class__9_ = "wcw_s14x_9b.shp" # provide a default value if unspecified

Output_Feature_Class__8_ = arcpy.GetParameterAsText(5)
if Output_Feature_Class__8_ == '#' or not Output_Feature_Class__8_:
    Output_Feature_Class__8_ = "wcw_s14x_8b.shp" # provide a default value if unspecified

Output_Feature_Class__7_ = arcpy.GetParameterAsText(6)
if Output_Feature_Class__7_ == '#' or not Output_Feature_Class__7_:
    Output_Feature_Class__7_ = "wcw_s14x_7b.shp" # provide a default value if unspecified

Output_Feature_Class__6_ = arcpy.GetParameterAsText(7)
if Output_Feature_Class__6_ == '#' or not Output_Feature_Class__6_:
    Output_Feature_Class__6_ = "wcw_s14x_6bshp.shp" # provide a default value if unspecified

Output_Feature_Class__5_ = arcpy.GetParameterAsText(8)
if Output_Feature_Class__5_ == '#' or not Output_Feature_Class__5_:
    Output_Feature_Class__5_ = "wcw_s14x_5b.shp" # provide a default value if unspecified

Output_Feature_Class__4_ = arcpy.GetParameterAsText(9)
if Output_Feature_Class__4_ == '#' or not Output_Feature_Class__4_:
    Output_Feature_Class__4_ = "wcw_s14x_4bshp.shp" # provide a default value if unspecified

Output_Feature_Class__3_ = arcpy.GetParameterAsText(10)
if Output_Feature_Class__3_ == '#' or not Output_Feature_Class__3_:
    Output_Feature_Class__3_ = "wcw_s14x_3b.shp" # provide a default value if unspecified

Output_Feature_Class__2_ = arcpy.GetParameterAsText(11)
if Output_Feature_Class__2_ == '#' or not Output_Feature_Class__2_:
    Output_Feature_Class__2_ = "wcw_s14x_2b.shp" # provide a default value if unspecified

Output_Feature_Class = arcpy.GetParameterAsText(12)
if Output_Feature_Class == '#' or not Output_Feature_Class:
    Output_Feature_Class = "wcw_s14_1b.shp" # provide a default value if unspecified

Input_RTP = arcpy.GetParameterAsText(13)
if Input_RTP == '#' or not Input_RTP:
    Input_RTP = "C:\\Kelsey\\Fall_2016\\WC_1m\\Sept_2014\\elev_b\\wc_s14_b_rtp.shp" # provide a default value if unspecified

# Local variables:
v1 = Input_RTP
v2 = Input_RTP
v3 = Input_RTP
v4 = Input_RTP
v5 = Input_RTP
v6 = Input_RTP
v7 = Input_RTP
v8 = Input_RTP
v9 = Input_RTP
v10 = Input_RTP
v11 = Input_RTP
v12 = Input_RTP

# Process: Feature Class to Feature Class
arcpy.FeatureClassToFeatureClass_conversion(Input_RTP, Output_Folder, Output_Feature_Class, "\"GRIDCODE\" =  1", "ID \"ID\" true true false 10 Long 0 10 ,First,#,C:\\Kelsey\\Fall_2016\\WC_1m\\Sept_2014\\elev_b\\wc_s14_b_rtp.shp,ID,-1,-1;GRIDCODE \"GRIDCODE\" true true false 10 Long 0 10 ,First,#,C:\\Kelsey\\Fall_2016\\WC_1m\\Sept_2014\\elev_b\\wc_s14_b_rtp.shp,GRIDCODE,-1,-1", "")

# Process: Feature Class to Feature Class (2)
arcpy.FeatureClassToFeatureClass_conversion(Input_RTP, Output_Folder, Output_Feature_Class__2_, "\"GRIDCODE\" =   2", "ID \"ID\" true true false 10 Long 0 10 ,First,#,C:\\Kelsey\\Fall_2016\\WC_1m\\Sept_2014\\elev_b\\wc_s14_b_rtp.shp,ID,-1,-1;GRIDCODE \"GRIDCODE\" true true false 10 Long 0 10 ,First,#,C:\\Kelsey\\Fall_2016\\WC_1m\\Sept_2014\\elev_b\\wc_s14_b_rtp.shp,GRIDCODE,-1,-1", "")

# Process: Feature Class to Feature Class (3)
arcpy.FeatureClassToFeatureClass_conversion(Input_RTP, Output_Folder, Output_Feature_Class__3_, "\"GRIDCODE\" =    3", "ID \"ID\" true true false 10 Long 0 10 ,First,#,C:\\Kelsey\\Fall_2016\\WC_1m\\Sept_2014\\elev_b\\wc_s14_b_rtp.shp,ID,-1,-1;GRIDCODE \"GRIDCODE\" true true false 10 Long 0 10 ,First,#,C:\\Kelsey\\Fall_2016\\WC_1m\\Sept_2014\\elev_b\\wc_s14_b_rtp.shp,GRIDCODE,-1,-1", "")

# Process: Feature Class to Feature Class (4)
arcpy.FeatureClassToFeatureClass_conversion(Input_RTP, Output_Folder, Output_Feature_Class__4_, "\"GRIDCODE\" =  4", "ID \"ID\" true true false 10 Long 0 10 ,First,#,C:\\Kelsey\\Fall_2016\\WC_1m\\Sept_2014\\elev_b\\wc_s14_b_rtp.shp,ID,-1,-1;GRIDCODE \"GRIDCODE\" true true false 10 Long 0 10 ,First,#,C:\\Kelsey\\Fall_2016\\WC_1m\\Sept_2014\\elev_b\\wc_s14_b_rtp.shp,GRIDCODE,-1,-1", "")

# Process: Feature Class to Feature Class (5)
arcpy.FeatureClassToFeatureClass_conversion(Input_RTP, Output_Folder, Output_Feature_Class__5_, "\"GRIDCODE\" =  5", "ID \"ID\" true true false 10 Long 0 10 ,First,#,C:\\Kelsey\\Fall_2016\\WC_1m\\Sept_2014\\elev_b\\wc_s14_b_rtp.shp,ID,-1,-1;GRIDCODE \"GRIDCODE\" true true false 10 Long 0 10 ,First,#,C:\\Kelsey\\Fall_2016\\WC_1m\\Sept_2014\\elev_b\\wc_s14_b_rtp.shp,GRIDCODE,-1,-1", "")

# Process: Feature Class to Feature Class (6)
arcpy.FeatureClassToFeatureClass_conversion(Input_RTP, Output_Folder, Output_Feature_Class__6_, "\"GRIDCODE\" =   6", "ID \"ID\" true true false 10 Long 0 10 ,First,#,C:\\Kelsey\\Fall_2016\\WC_1m\\Sept_2014\\elev_b\\wc_s14_b_rtp.shp,ID,-1,-1;GRIDCODE \"GRIDCODE\" true true false 10 Long 0 10 ,First,#,C:\\Kelsey\\Fall_2016\\WC_1m\\Sept_2014\\elev_b\\wc_s14_b_rtp.shp,GRIDCODE,-1,-1", "")

# Process: Feature Class to Feature Class (7)
arcpy.FeatureClassToFeatureClass_conversion(Input_RTP, Output_Folder, Output_Feature_Class__7_, "\"GRIDCODE\" =    7", "ID \"ID\" true true false 10 Long 0 10 ,First,#,C:\\Kelsey\\Fall_2016\\WC_1m\\Sept_2014\\elev_b\\wc_s14_b_rtp.shp,ID,-1,-1;GRIDCODE \"GRIDCODE\" true true false 10 Long 0 10 ,First,#,C:\\Kelsey\\Fall_2016\\WC_1m\\Sept_2014\\elev_b\\wc_s14_b_rtp.shp,GRIDCODE,-1,-1", "")

# Process: Feature Class to Feature Class (8)
arcpy.FeatureClassToFeatureClass_conversion(Input_RTP, Output_Folder, Output_Feature_Class__8_, "\"GRIDCODE\" =  8", "ID \"ID\" true true false 10 Long 0 10 ,First,#,C:\\Kelsey\\Fall_2016\\WC_1m\\Sept_2014\\elev_b\\wc_s14_b_rtp.shp,ID,-1,-1;GRIDCODE \"GRIDCODE\" true true false 10 Long 0 10 ,First,#,C:\\Kelsey\\Fall_2016\\WC_1m\\Sept_2014\\elev_b\\wc_s14_b_rtp.shp,GRIDCODE,-1,-1", "")

# Process: Feature Class to Feature Class (9)
arcpy.FeatureClassToFeatureClass_conversion(Input_RTP, Output_Folder, Output_Feature_Class__9_, "\"GRIDCODE\" =  9", "ID \"ID\" true true false 10 Long 0 10 ,First,#,C:\\Kelsey\\Fall_2016\\WC_1m\\Sept_2014\\elev_b\\wc_s14_b_rtp.shp,ID,-1,-1;GRIDCODE \"GRIDCODE\" true true false 10 Long 0 10 ,First,#,C:\\Kelsey\\Fall_2016\\WC_1m\\Sept_2014\\elev_b\\wc_s14_b_rtp.shp,GRIDCODE,-1,-1", "")

# Process: Feature Class to Feature Class (10)
arcpy.FeatureClassToFeatureClass_conversion(Input_RTP, Output_Folder, Output_Feature_Class__10_, "\"GRIDCODE\" =  10", "ID \"ID\" true true false 10 Long 0 10 ,First,#,C:\\Kelsey\\Fall_2016\\WC_1m\\Sept_2014\\elev_b\\wc_s14_b_rtp.shp,ID,-1,-1;GRIDCODE \"GRIDCODE\" true true false 10 Long 0 10 ,First,#,C:\\Kelsey\\Fall_2016\\WC_1m\\Sept_2014\\elev_b\\wc_s14_b_rtp.shp,GRIDCODE,-1,-1", "")

# Process: Feature Class to Feature Class (11)
arcpy.FeatureClassToFeatureClass_conversion(Input_RTP, Output_Folder, Output_Feature_Class__11_, "\"GRIDCODE\" =  11", "ID \"ID\" true true false 10 Long 0 10 ,First,#,C:\\Kelsey\\Fall_2016\\WC_1m\\Sept_2014\\elev_b\\wc_s14_b_rtp.shp,ID,-1,-1;GRIDCODE \"GRIDCODE\" true true false 10 Long 0 10 ,First,#,C:\\Kelsey\\Fall_2016\\WC_1m\\Sept_2014\\elev_b\\wc_s14_b_rtp.shp,GRIDCODE,-1,-1", "")

# Process: Feature Class to Feature Class (12)
arcpy.FeatureClassToFeatureClass_conversion(Input_RTP, Output_Folder, Output_Feature_Class__12_, "\"GRIDCODE\" =  12", "ID \"ID\" true true false 10 Long 0 10 ,First,#,C:\\Kelsey\\Fall_2016\\WC_1m\\Sept_2014\\elev_b\\wc_s14_b_rtp.shp,ID,-1,-1;GRIDCODE \"GRIDCODE\" true true false 10 Long 0 10 ,First,#,C:\\Kelsey\\Fall_2016\\WC_1m\\Sept_2014\\elev_b\\wc_s14_b_rtp.shp,GRIDCODE,-1,-1", "")

