# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Classes_Aspect.py
# Created on: 2019-01-15 09:50:58.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: Classes_Aspect <Output_Folder> <Input_raster> <RTP_DEM> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

