# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# int_pred.py
# Created on: 2018-09-27 14:11:00.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Local variables:
Slope_tif = "Slope.tif"
slope_pp5_tif = "E:\\April18\\RF\\Int_Predictors\\f17\\temp\\slope_pp5.tif"
f17_slope_int_tif = "E:\\April18\\RF\\Int_Predictors\\f17\\temp\\Slope.tif"

# Process: Raster Calculator
#arcpy.gp.RasterCalculator_sa("\"%Slope_tif%\" + 0.5", slope_pp5_tif)

# Process: Int
slope_pp5_tif = "E:\\April18\\RF\\Int_Predictors\\f17\\temp\\slope_pp5.tif"
f17_slope_int_tif = "E:\\April18\\RF\\Int_Predictors\\f17\\Slope.tif"
arcpy.gp.Int_sa(slope_pp5_tif, f17_slope_int_tif)

elevation_pp5_tif = "E:\\April18\\RF\\Int_Predictors\\f17\\temp\\elevation_pp5.tif"
f17_elevation_int_tif = "E:\\April18\\RF\\Int_Predictors\\f17\\Elevation.tif"
arcpy.gp.Int_sa(elevation_pp5_tif, f17_elevation_int_tif)

TPI_pp5_tif = "E:\\April18\\RF\\Int_Predictors\\f17\\temp\\TPI_pp5.tif"
f17_TPI_int_tif = "E:\\April18\\RF\\Int_Predictors\\f17\\TPI.tif"
arcpy.gp.Int_sa(TPI_pp5_tif, f17_TPI_int_tif)

aspect_pp5_tif = "E:\\April18\\RF\\Int_Predictors\\f17\\temp\\aspect_pp5.tif"
f17_aspect_int_tif = "E:\\April18\\RF\\Int_Predictors\\f17\\Aspect.tif"
arcpy.gp.Int_sa(aspect_pp5_tif, f17_aspect_int_tif)

a_LSDM_tt_pp5_tif = "E:\\April18\\RF\\Int_Predictors\\f17\\temp\\a_LSDM_tt_pp5.tif"
f17_a_LSDM_tt_int_tif = "E:\\April18\\RF\\Int_Predictors\\f17\\a_LSDM.tif"
arcpy.gp.Int_sa(TPI_pp5_tif, f17_a_LSDM_tt_int_tif)
